### Get all alert rules
GET http://localhost:3000/alerts
Accept: application/json

### Create a new alert rule
POST http://localhost:3000/alerts
Content-Type: application/json

{
  "name": "High CPU Usage",
  "description": "Alert for high CPU usage",
  "enabled": true,
  "conditions": [
    {
      "field": "cpu",
      "operator": "greaterThan",
      "value": "80"
    }
  ],
  "notificationChannels": [
    {
      "type": "email",
      "config": {
        "to": "admin@example.com"
      }
    }
  ]
}

### Create a new alert rule
POST http://localhost:3000/alerts
Content-Type: application/json

{
  "name": "PATH method contained",
  "description": "Triggered when PATH method is contained",
  "enabled": true,
  "conditions": [
    {
      "field": "message",
      "operator": "contains",
      "value": "PATCH"
    }
  ],
  "notificationChannels": [
    {
      "type": "email",
      "config": {
        "to": "admin@example.com"
      }
    }
  ]
}

### Create a new alert rule
POST http://localhost:3000/alerts
Content-Type: application/json

{
  "name": "DELETE method contained",
  "description": "Triggered when PATH method is contained",
  "enabled": true,
  "conditions": [
    {
      "field": "message",
      "operator": "contains",
      "value": "DELETE"
    }
  ],
  "notificationChannels": [
    {
      "type": "slack",
        "config": {
            "url": "slack://webhook"
        }
    }
  ]
}

### Update an existing alert rule
@alertRuleId = 672f471dbd9b4cb06751acf5
PUT http://localhost:3000/alerts/{{alertRuleId}}
Content-Type: application/json

{
  "name": "High CPU Usage Updated",
  "description": "Updated alert for high CPU usage",
  "enabled": true,
  "conditions": [
    {
      "field": "cpu",
      "operator": "greaterThan",
      "value": "85"
    }
  ],
  "notificationChannels": [
    {
      "type": "email",
      "config": {
        "to": "admin@example.com"
      }
    }
  ]
}

### Delete an alert rule
DELETE http://localhost:3000/alerts/{{alertRuleId}}